### ISSUE TITLE
Rename IPersonEffect to IPersonCondition

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#1103]
It is more representable and reduce confusion. Monogame has effects as shader wrapper.
Types to rename:
- `IPersonEffect` to `IPersonCondition`.
- `IEffectsModule` to `IConditionModule`.
- some else

This changes must be done in the `master` branch.

**Comment by flor3sc0** [comment]
- some else.
ISurvivalStatEffect ?
