### ISSUE TITLE
leather-armor переименовать в leather-jacket

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#183]
1. Схему.
2. Английское наименование.
3. Название иконки.
4. Название визуализации.

**Comment by Kin51** [comment]
Уточняю:
2. Английское наименование - что конкретно имеется в виду?
4. Название визуализации - это именно дропающийся предмет внутри юнити, так?

**Comment by kreghek** [comment]
Визуализацией предмета я называю объект, который рендерится на персонаже в игровом мире. Условно можно выделить схему, иконку и префаб визуализации. Лежат тут (Zilon.Client\Assets\Resources\VisualProps)
