### ISSUE TITLE
Избавиться от ProcessDefence и ProcessArmor

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#225]
Эти методы нужны только для того, чтобы выбрасывать события. Нужно сделать выброс событий там, где генерируются ситуации, когда событие нужно. Предположительно это TacticalActUsageServive. Возможно, лучше будет перераспределить обязанности во время использования действия.

**Comment by Kin51** [comment]
А разве не будет лучше наоборот, оставить подобные действия в специально отведенном методе? Если код для этих действий нужно будет дополнить - придется перебегать во всех местах, где он используется и менять всё руками. Там могут быть достаточно большие изменения, то есть код будет просто дублироваться и распухать еще больше, безо всякой на то причины.
Я бы наоборот, подумал о дополнении и улучшении уже существующего метода, нет причины избавляться от правильного, уже работающего в коде метода.

**Comment by kreghek** [comment]
Методы, в которых централизовано будет выполняться какая-то операция - да, это хорошо, вы правы.
Конкретно эти два - просто костыль, который позволяется отбрасывать нужные события актёра, в то время, когда операция выполняется в сервисе.

Если честно, пока нет конкретных идей, как улучшить. Предположительно, нужно разгрузить сервис TacticalActUsageService и, возможно, наполнить ProcessDefence и ProcessArmor. Пусть задача повисит пока до конца этапа разработки. Позже вернёмся к задаче и решим, что делать.

**Comment by kreghek** [comment]
Нужно сделать совместно с #125 и #127. Целевые методы задачи были введены, чтобы сообщить клиенту об исходе. Нужно упразднить так, чтобы на клиенте всё ещё оставалась возможность визуализации.

**Comment by kreghek** [comment]
Сделано в рамках других задач. После ввода директора сцены.
