### ISSUE TITLE
Мощь экипировки

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#237]
Раньше был такой параметр предметов экипировки, как Power (мощь/качество/уровень). Он был процентом, который применялся к урону оружия, поглощению брони, эффективности лечения книг лечения. Все эти значения были из диапазона больших чисел и это было возможно.

Сейчас все значения эффективности - это броски кубов. Величины редко выходят за 10. И механизм с процентами не подходит. Нужно подумать, как теперь можно использовать мощь.

**Comment by Kin51** [comment]
1) Вариант с процентами не стал невозможным. Высокая мощь - большой процент от броска, после броска добавляем сверху процентик и порядок.
2) Вариант с сухой цифрой. 
  2.1) Добавлять цифру перед броском - кубик выбрасывает не условные 1-6, а 2-6/3-6
  2.2) Добавлять цифру после броска - кубик выбрасывает 1-6, сверху добавим +1.
Единственный вопрос пожалуй в верхнем ограничении величин - если оно есть, то нужна дополнительная проверка, а иначе можно и не волноваться совсем.

**Comment by kreghek** [comment]
Спасибо. Ознакомлюсь.

В целом, нужна система, которая отличала бы один и тот же предмет (предметно, короткий меч) разного уровня мощности. То есть между 1 и 2 уровнем мощи было минимальное отличие (например, +1 к верхней границе). Но 10 уровень мощи меча уверенно доминировал над 1, и 20 над 10 (пример, 1d6 для первого уровня и 1d6+6 на 10).

**Comment by Kin51** [comment]
То есть мощь это по сути своей - точка из других игр? Предмет можно будет самостоятельно улучшать  с помощью особых предметов? И шанс поломки тоже будет расти от уровня точки, так?
Можно еще прописать руками баланс и определить что куда - тогда между +1 и +2 может оказаться не 10% разницы, а например, 40%, и условная точка до +5 не будет делать погоды, а +6 будет практически критична. Просто, +6 на 10 уровне не вяжется с системой +1/уровень.

Может, сделать специальное место или комнату, где можно точить предметы? Ограниченно, само собой, скажем 2-3 попытки на все предметы, игрок сам будет думать, что и когда точить.

**Comment by kreghek** [comment]
Не понимаю, что значит точка. Это уровень.

Предметы можно будет улучшать. На шлема ставить датчики. На винтовки - прицелы. Но это позже.
Точить - я бы не делал. Улучшение только при помощи других модулей. Или смена одного длинного меча другим таким же с более высокой мощь (качеством, уровнем).

Руками задать градацию можно. Но да, не вяжется с +6 на 10 уровне. Будут предметы разного уровня, но с одинаковой статой.

От уровня зависит запас прочности. Чем выше уровень, тем дольше можно пользоваться предметом. Подразумевается, что более качественные предметы работают эффективнее и дольше изнашиваются.

**Comment by Kin51** [comment]
Просто, много модулей на тот же меч придумать не получится. А еще возникнут логичные вопросы - почему прицел даёт урон, или почему рукоять даёт урон. Только что пришла мысль о качестве патронов, вот там уж напрямую урон будет увеличиваться более логично.
Просто, если уровень никак не улучшается - игра будет сильно рандомная. Ну да, мне выпало +9 на первом этаже с запасом прочности 512 и теперь я непобедимая машина-убийца. И обратно - выпадает +0 и ты вынужден начинать сначала, потому что через две мыши у тебя просто ломается оружие. Разве не лучше дать весь/больше контроля над игровым процессом пользователю? Засыпать его лутом всех видов плюсов это прекрасно, но смысла в этом будет, как в казино.
А насчет модулей еще. При большой вариации оружия и модулей - найти нужную пару будет запарно. Чем дальше - тем больше контента, а значит больше нерабочих сочетаний "вещь-модуль", не станем же мы в самом деле прикреплять лазерный указатель от шлема к мечу и давать ему за это плюс?

**Comment by kreghek** [comment]
Модули не обязательно должны увеличивать урон. Сейчас в боёвке есть шанс попадания, множество атак одним оружием (выбирать нельзя, но отросток в виде жёлтого меча внизу слева мне об этом напоминает:) ) и разные типы нападения (тактическое, яростное, фокусированное и т.д.).
Много модулей и не нужно. Идея модулей в том, чтобы расширять возможности предметов экипировки. Но для самих предметов хотелось бы видеть что-то типа уровней мощи/качества.
Если уровень не улучшается, будет явный гринд или крафт. А уровнем выпадения можно управлять. Чтобы +9 в первой комнате не сломало игру.
Нерабочие сочетания можно разрешить более управляемой системой подбора - торговлей (планируется делать), крафтом (планируется, наработки есть) или квестами (тут пока глухо).

**Comment by kreghek** [comment]
Текущий вариант:
1. Вся экипировка делится по качеству: брак (defect), серийная, предмет мастера (mastercraft). Брак и местеркрафт будут реролл по эффективности соответственно в минус или в плюс соответственно. Так же чем выше качество, тем больше прочность предмета. То есть более качественные предметы дольше прослужат и реже нуждаются в ремонте.
2. Следующая ось: обычный, мистический. Мистические предметы будет иметь бонус к характеристикам предмета или персонажа. Мистические вещи не могут быть серийными.
3. Следующая ось: проклятые вещи. Проклятые вещи будут иметь отрицательный бонус к характеристикам предмета или персонажа. Проклятые - это обязательно мистические. Отрицательный бонус не отменяет, а дополняет положительный.
4. Отдельная категория - легендарные предметы. Для таких будет фиксированное качество, набор положительных и отрицательных бонусов.

Шкала ценности предметов:
1. Брак
2. Серийный
3. Мастерский
4. Проклятый бракованный
5. Мистический бракованный
6. Проклятый мастерский
7. Мистический мастерский
8. Легендарный
