### ISSUE TITLE
Не работает посох

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#246]
Проверялось на конкурсной сборке. Проверялось в 5 кластере на гоблине.

Мана есть, а выстрелить из посоха не получилось.

**Comment by Kin51** [comment]
Хочу изучить эту проблему.
Нужна подсказка, перерыл всё что только можно.
Где искать логику посоха?

**Comment by kreghek** [comment]
Сейчас посохи, луки и пистолет работают одинаково. Если в инвентаре есть расходник нужного типа (калибра), то атака происходит. Посохи должны использовать ману. Использование происходит в TacticalActUsageService. Там же изымается расходник.

**Comment by Kin51** [comment]
Протестил лук - он работает, стрелы изымаются, удар идет. До посохов пока не дошел.
Из интересного - при переходе с 3 уровня на 4 автоход завис и преспокойно ходил сам без моего участия, остановился только вплотную у сундука.

**Comment by kreghek** [comment]
Чтобы упростить себе задачу, можно изначально в инвентарь подкинуть пару посохов и маны.

Для этого в SecorVM.CreateHumanActorVm()
```
if (_personManager.Person == null)
{
...
// здесь добавить строки
AddEquipmentToActor(inventory, "fireball-staff");
            AddEquipmentToActor(inventory, "shadow-staff");
            AddResourceToActor(inventory, "mana", 10);
}
```

**Comment by kreghek** [comment]
Сейчас в мастере не воспроизводится.
