### ISSUE TITLE
Автоматическое перемещение персонажа

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#269]
Сейчас персонаж делает ход при клике. Крайне не удобно.

Нужно сделать так, чтобы персонаж перемещался, пока не дойдёт до указанной точки или пока не встретит препятствие.

**Comment by Kin51** [comment]
И как это будет? Особенно с пошаговой системой? Ну то есть, игрок жмет на 6 клеток рядом и по пути его убивают, потому что автоход и монстры тоже ходят?

**Comment by kreghek** [comment]
Неудобства начинаются, когда персонаж начинает бродить по коридорам или комнатам. Когда игрок видит монстров, там включается тактическая составляющая и игрок ходит по 1 клетке.

По-хорошему, нужно будет прерывать перемещение при некоторых событиях:
1. Обнаружение монстра в зоне видимости (после ввода тумана войны).
2. Получение урона.
3. Обнаружение сундуков, лута.
4. Что-то ещё.

Но тут нужно пробовать, как удобнее. При необходимости, дополню эту задачу или заведу отдельные задачи.

**Comment by kreghek** [comment]
Можно посмотреть, как это работает в ветке feature-269-automove

**Comment by Kin51** [comment]
Главное, чтобы не было телепортов или ускорений во время этого режима игры - геймплей пострадает, и достаточно сильно. Хотя всё еще не очень вижу смысл в этой фишке, например, не совсем понимаю как это будет вязаться с дверями, на открытие которых тратится ход - если рядом нет врагов, на этот ход игроку всё равно, а если есть - тактический режим и так работает, и каждый ход важен. 
В roguelike (рогаликах), которые я играл, ничего подобного не было - от автохода до стены не было прока. Но например, в ToME есть фишка с автоисследованием локации, на случай, если сильно надоело играть - однако ей не спешили пользоваться, в драке она ставила тебя в неудобное положение (редко, но смерть персонажа высокого уровня от случайности себе дороже). По сути, персонаж там последовательно исследовал локацию, открывая все возможные скрытые места, прерываясь на обнаружении сундуков и монстров, а если локация была исследована - добегал героем до перехода с локации/на следующую локацию.

А генерация коридоров это отдельная песня, я бы скорее предложил поправить код генерации уровня, порой через всю игру тянется один коридор и чуть ли не параллельно с ним еще один такой же, ходить в нём неудобно, да и не очень осмысленно - это же коридор.
А еще, может, управление с клавиатуры? По хексам конечно не слишком удобно, но как есть. На тот же NumPad его спроектировать, каким-нибудь хитрым образом. Сейчас выходят много кликов с мыши + нужно выжидать анимацию перехода по хексу персонажа, достаточно мудрёная система.

**Comment by kreghek** [comment]
Я вдохновлялся Adom и Shardstone. Там есть автоперемещение, если нет препятствий и противников, если грубо.

Генерация уровня сейчас плохая, согласен. В этом этапе проведу работы.

Управление с клавиатуры - спасибо. Совсем забыл про эту хотелку пользователей. Заведу задачу. Попробовать стоит. Управление с клавиатуры ожидаемо игроками, а цена реализации низка.

Ещё понаблюдаю автопередвижение. Всё ещё нуждается в доработке. В конце концов это не сильно влияет на то, что уже есть.

**Comment by kreghek** [comment]
Сейчас в ветке по задаче сделано автоперемещение. Автоперемещение возможно, если на расстоянии 5 узлов в прямой видимости от игрока нет монстров.

Автоперемещение ломается из-за исключения в логике монстров.
```
InvalidOperationException: Попытка переместиться в заблокированную ячейку
```
Предположительно с этим же связан баг #145. Сначала нужно решить его, и понаблюдать за перемещением.
