### ISSUE TITLE
Заменить спрайты стен

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#272]
Сейчас стена - это текстура кирпичей, наложенная на грань гекса. Выглядит стрёмно.

Нужно отрисовать стены сбоку. Первоначально попробовать вариант с 2 стенами - на верхнюю грань и на все остальные (зеркалить). Автотайлинг пока не делать.

**Comment by Kin51** [comment]
Интересует вопрос, а спрайты какие-нибудь нужно менять? Не очень удачные или которые не нравятся? Я не то чтобы умею рисовать, но попытка не пытка, вдруг получится!

**Comment by kreghek** [comment]
Да там сейчас один спрайт. Просто повёрнут понемногу.
Изначально предполагалось, что окружение будет в изометрии. Типа такого:
![image](https://user-images.githubusercontent.com/2405499/51994557-a0797000-24e3-11e9-8428-e7caa5d92d3e.png)
Ну и конечно же, высший пилотаж
![image](https://user-images.githubusercontent.com/2405499/51994616-c30b8900-24e3-11e9-9cbb-8f012bc950c8.png)
Только в нашем случае для начала нужно попробовать 2 спрайта.
![image](https://user-images.githubusercontent.com/2405499/51995413-3f529c00-24e5-11e9-8e16-ab7b75fa2840.png)
Нужно будет красную и одну синюю. Я потом синие отзеркалю.

**Comment by kreghek** [comment]
Согласен. Всё должно быть в одной стилистике. Сейчас всё спрайты - формальные и надёрганы откуда попало.
А у вас в чём больше скилла? Я бы попробовал вектор. План отступления - пиксельарт.

**Comment by Kin51** [comment]
У меня нет скилла, только энтузиазм и не более :D 
А в векторе я совсем плох. В пиксельарте несколько проще добиться чего-то конкретного.

**Comment by kreghek** [comment]
Итоговый вариант выглядит так

![image](https://user-images.githubusercontent.com/2405499/61478655-1ef79a80-a9bc-11e9-95e2-a7d024a18c97.png)

**Comment by kreghek** [comment]
![image](https://user-images.githubusercontent.com/2405499/61478720-56fedd80-a9bc-11e9-8f15-31de5dcd86e3.png)
