### ISSUE TITLE
Добавить усиление жажды при употреблении некоторых продуктов

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#274]
Есть сухой паёк. И сыр.

Нужно попробовать сделать, чтобы при употреблении эти продукты увеличивали жажду. Возможно, конкретно они и не будут снижать в конечном счёте, но механику попробовать стоит.

**Comment by kreghek** [comment]
Сейчас все продукты только увеличивают показатели сытости/жажды/хп. Нужно дописать обратное влияние. Использовать перечисление PersonRuleDirection. После этого, да, дополнить схемы.

Возникла идея снижения параметров, чтобы был выбор, какой параметр принести в жертву. Иногда еды дропается много, а воды - мало. Зафиксировал в задаче, чтобы не забыть.

**Comment by Kin51** [comment]
Посмотрел эту проблему поближе. Сейчас лежит там себе этот PersonRuleDirection, да не используется. Проблема в том, что их как-то нетривиально подвязывать к делу:
- Сейчас играет роль только Type, который Lesser/Normal и тд. Соответственно, если прикручивать Direction, то может получится -Lesser (Минус лессер), что не вяжется, как его обрабатывать, если он не из enum PersonalRuleType?

Мысли:
- как-то продолжить и оставить два списка, как есть сейчас - Тип отдельно, Direction отдельно, но тогда нужно понять как их обрабатывать в коде
- убрать Direction и дополнить Типы отрицательными значениями
Прошу совета, не знаю, как делать правильно.
PS: если в коде любого пополнения хп поменять +4 на -4 - он ломается, так как value не может быть меньше 0. Не сыграет ли это злую шутку дальше, ведь -10 тоже меньше нуля.

**Comment by kreghek** [comment]
Нужно использовать `PersonRuleDirection`. По уровню правила брать значение. Например, `PropMetrics.SurvivalLesserRestoreValue`. По `PersonRuleDirection` - что с ним делать. Восстанавливать или понижать.

В схемах по умолчанию будет использоваться положительное значение. Направление даже указывать не придётся.

Для восстановления и понижения характеристик используются разные методы: `ISurvivalData.RestoreStat(...)` и `ISurvivalData.DecreaseStat(...)`. В зависимости от направления выбирать нужный.

**Comment by Kin51** [comment]
Я так понимаю, дублирование методов на уровне актера ни к чему не приведет?
Там сейчас есть RestoreStat/Satiety/Water/SurvivalStatInner/Hp, не стоит же рядом делать тоже самое, только для уменьшения? В идеале, преобразовать текущие методы, чтобы они работали исходя из PersonRuleDirection?

**Comment by kreghek** [comment]
Сейчас есть изменение ХП от экипировки. Рекомендую сделать аналогично.
