### ISSUE TITLE
Refactor GlobeWorldVM.Start()

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#552]
I've selected [**GlobeWorldVM.Start()**](https://github.com/kreghek/Zilon_Roguelike/blob/62873c9b6a0ee263c7608fe8e86deb48fb4def11/Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs#L51-L243) for refactoring, which is a unit of **139** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by valentk777** [comment]
Hello, I would like to try this task

**Comment by kreghek** [comment]
Hi! Welcome!

Just try to decompose this huge method to smaller 15 LoC methods int this class.
