### ISSUE TITLE
Refactor 15 lines occurring 2 times in 2 files: FixCompactRoomGeneratorRandomSource.cs, FixLargeRoomGeneratorRandomSource.cs

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#561]
I've selected for refactoring 15 lines of code which are duplicated in 2 file(s) ([1](https://github.com/kreghek/Zilon_Roguelike/blob/61945f58e30a99b50daaf4d53d66bb1a367eb743/Zilon.Core/Zilon.Core/MapGenerators/RoomStyle/FixCompactRoomGeneratorRandomSource.cs#L35-L82), [2](https://github.com/kreghek/Zilon_Roguelike/blob/61945f58e30a99b50daaf4d53d66bb1a367eb743/Zilon.Core/Zilon.Core/MapGenerators/RoomStyle/FixLargeRoomGeneratorRandomSource.cs#L33-L79)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by kreghek** [comment]
Ввести базовый абстрактный класс FixedRoomGeneratorRandomSource

**Comment by luisvita** [comment]
I can give this a try but I don't speak Russian.

**Comment by kreghek** [comment]
I will be grateful for the help.
