### ISSUE TITLE
Refactor 12 lines occurring 2 times in 2 files: GlobeWorldVM.cs, SectorVM.cs

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#562]
I've selected for refactoring 12 lines of code which are duplicated in 2 file(s) ([1](https://github.com/kreghek/Zilon_Roguelike/blob/61945f58e30a99b50daaf4d53d66bb1a367eb743/Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs#L337-L363), [2](https://github.com/kreghek/Zilon_Roguelike/blob/61945f58e30a99b50daaf4d53d66bb1a367eb743/Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs#L156-L182)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by kreghek** [comment]
Ввести базовый MonoBehaviour для объектов, которые выполняют команды. Пусть называется ComandExecutorViewModelBase. Абстрактным делать не нужно, потому что это MonoBeh.

**Comment by dcparga** [comment]
Just wondering... I wanted to fix it, but I don't see any project/solution for the client side. Am I missing something?

**Comment by kreghek** [comment]
> Just wondering... I wanted to fix it, but I don't see any project/solution for the client side. Am I missing something?

Client is Unity. Its generate solution then editor launched.

**Comment by kreghek** [comment]
Сейчас неактуально, т.к. глобальная карта упразднена.
