### ISSUE TITLE
Хелловин-акция 2019

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#565]
Нужно подготовить что-нибудь акционое. Пока на этапе обсуждения. Идеи можно указывать в комментариях. Наиболее интересные и сформировавшиеся будут попадать в этот список.

# Идеи
1. Добавить монстра тыкву. Пусть они генерятся в диких секторах. А ближе к 02.11 начинают генериться чаще.
2. Добавить предмет Тыкву. Увеличивать дроп к 02.11. Предмет можно надеть на голову или съесть. Такой комбинации ещё не было - и часть экипировки и провиант.
3. Добавить постоянную ночь. Требуются значительные доработки. Для этого на каждый спрайт игрового предмета накладывать дополнительный темно-синий цвет.

**Comment by Mentall** [comment]
В хэллоувинскую неделю поздравлять игрока. В любом году.

**Comment by kreghek** [comment]
Ещё тема: сделать тыкву-шлем, которая ест игрока. Сделать проклятые предметы достаточно просто. Добавить новый дебафф, отнимающий здоровье, тоже просто.

**Comment by kreghek** [comment]
Успел сделать только одну задачу. Остальное - в следующий раз.
