### ISSUE TITLE
Восстановить расчёт покрытия тестами

### ISSUE THREAD

**Issue by kreghek** [kreghek/Zilon_Roguelike#653]
В расчёт покрытия включить:
1. Модульные тесты
2. Спецификации
3. Модульные, но с Di.

**Comment by iRumba** [comment]
> Модульные, но с Di.

Это как?

**Comment by kreghek** [comment]
> > Модульные, но с Di.
> 
> Это как?

Есть просто набор тестов на команды, в которых я использовал DI для инстанцирования сервисов. Вышло не очень, но переписать на нормальные параллельные модульные тесты пока руки не доходят.

**Comment by kreghek** [comment]
#862 В этом MR сделан сбор покрытия в coverall.io
